spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  artemis:
    mode: embedded
    embedded:
      enabled: true

  profiles:
    active: prod #  dev = H2, prod = MySQL
server:
  port: 8081
